#!/bin/bash
#list of terminal short cuts for vscode

echo "      "
echo "      ---terminal short cuts----"
echo "      "
echo "      New tab --- command + T"
echo "      New window --- command + N"
echo "      Jump word --- option + left/right arrow"
echo "      Beginning of line --- control + A"
echo "      End of line -- control + E"
echo "      Delete line --- control + V"
echo "      Delete to end of line --- control + K"
echo "      Delete to beginning of word --- control + W"
echo "      Forward delete --- Fn + delete"
echo "      Switch 2 character --- control + T"
echo "      Find last input --- command + up/down arrow"
echo "      Split terminal --- command + D"
echo "      Unsplit terminal --- command + shft + D"
echo "      Copy --- cp ~<filepath> ."
echo "      "